services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tag-denton
    ports:
      - 8080:80
      - 8443:443
      - 9003:9003
    volumes:
      - .:/var/www/html
    environment:
      - ENABLE_XDEBUG=${ENABLE_XDEBUG:-0}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s